# Generated by Django 4.1.5 on 2023-02-02 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_follow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='UserFollow',
        ),
    ]
